image: python:3.12

stages:
  - build
  - deploy

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip

default:
  tags:
    - global

before_script:
  - python -m pip install --upgrade pip
  - pip install jupyter-book

build:
  stage: build
  script:
    - jupyter-book build neuroplatform-docs
  artifacts:
    paths:
      - _build/html

pages:
  stage: deploy
  script:
    - mv _build/html public
  artifacts:
    paths:
      - public
  only:
    - main

