# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: NeuroPlatform Documentation
author: FinalSpark
copyright: FinalSpark - 2024
logo: _static/logo.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: 'off'

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Information about where the book exists on the web
repository:
  url: https://github.com/FinalSpark-np/np-docs
  path_to_book: neuroplatform-docs
  branch: main  # Which branch of the repository should be used when creating links (optional)

html:
  favicon: _static/favicon.ico
  use_repository_button: true
 
